#!/usr/bin/env python3
"""Run every converted ground-truth circuit on the VM's Spectre.

Proves that tools/gt_convert.py produced decks a real Spectre accepts, and that each
LDO still regulates to the voltage its ngspice original was designed for.

    python tests/fixtures/ldo_gt/acceptance.py            # all of them
    python tests/fixtures/ldo_gt/acceptance.py ldo_gt ldo_v9_vldo

Bench (the same operating point the originals were characterised at):
    LDO  : vin = 1.05 V, load = 121 uA at vout; DC op + AC 100 Hz .. 100 MHz with
           mag=1 on the load current source, so the AC result is |Zout|.
    ISRC : vdd = 1.05 V, `out` forced to 0.5 V compliance; DC op reads the delivered
           current, AC reads the output admittance.
"""
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]
VMRUN = REPO / "tools" / "vmrun.sh"
WORK = HERE / "work"                      # git-ignored (.gitignore: work*/)

sys.path.insert(0, str(HERE.parent / "pmu_demo"))
from acceptance import read_dcop, read_ac          # noqa: E402  (same psfascii readers)

VIN = 1.05
ILOAD = "121u"
VCOMPLIANCE = 0.5

# DESIGN target: what each header comment / feedback divider says the rail should be.
# The residual is the OTA offset and the finite loop gain of the original circuit --
# v1_nmos is a source follower with a deliberately LOW loop gain, so its -5 % offset
# is a property of the circuit, not of this translation (see NGSPICE_REF below).
LDO_TARGET = {
    "ldo_gt": 0.900, "ldo_v1_nmos": 0.550, "ldo_v2_capless": 0.900,
    "ldo_v3_miller": 0.900, "ldo_v4_ffpsrr": 0.900, "ldo_v5_spur": 0.900,
    "ldo_v6_spur2": 0.900, "ldo_v7_esl": 0.900, "ldo_v8_dlc": 0.900,
    "ldo_v9_vldo": 1.000, "ldo_v10_3lc": 0.900, "ldo_classab": 0.900,
    "ldo_pzmig": 0.900, "ldo_qbow": 0.900, "ldo_swbleed": 0.900,
}

# TRANSLATION reference: vout of the ORIGINAL ngspice card at this same bench,
# measured with ngspice 46 (`.op`, vin=1.05 V, 121 uA load).  This is the number that
# tests the CONVERTER: Spectre must land on the same operating point, not merely on a
# plausible one.  Any deviation beyond ~0.1 % means gt_convert changed the circuit.
NGSPICE_REF = {
    "ldo_gt": 0.898482, "ldo_v1_nmos": 0.520381, "ldo_v2_capless": 0.901358,
    "ldo_v3_miller": 0.917967, "ldo_v4_ffpsrr": 0.898482, "ldo_v5_spur": 0.898482,
    "ldo_v6_spur2": 0.898482, "ldo_v7_esl": 0.898482, "ldo_v8_dlc": 0.898482,
    "ldo_v9_vldo": 0.995491, "ldo_v10_3lc": 0.898482, "ldo_classab": 0.900265,
    "ldo_pzmig": 0.898482, "ldo_qbow": 0.898482, "ldo_swbleed": 0.898481,
}


def subckts(path: pathlib.Path) -> list[str]:
    return re.findall(r"^subckt\s+(\S+)\s*\(", path.read_text(encoding="utf-8"), re.M)


def tb(libfile: str, name: str, isrc: bool) -> str:
    if isrc:
        # `out` is forced, so the AC observable is the CURRENT through the forcing
        # source: Vout:p / 1 V = the output admittance Yout.
        dut = f"xdut (vdd out) {name}\n" \
              f"Vdd (vdd 0) vsource dc={VIN}\n" \
              f"Vout (out 0) vsource dc={VCOMPLIANCE} mag=1\n"
        saves = "save out Vout:p Vdd:p"
    else:
        dut = f"xdut (vin vout) {name}\n" \
              f"Vin (vin 0) vsource dc={VIN}\n" \
              f"Iload (vout 0) isource dc={ILOAD} mag=1\n"
        saves = "save vout Vin:p"
    return f"""// generated by tests/fixtures/ldo_gt/acceptance.py -- bench for {name}
simulator lang=spectre
global 0

include "nmos_lv.scs"
include "pmos_lv.scs"
include "{libfile}"

{dut}
simOpts options temp=27 tnom=27
{saves}
dcOp dc write="op.dc"
acs ac start=100 stop=100M dec=5
"""


def run(tag: str, deck: str):
    d = WORK / tag
    d.mkdir(parents=True, exist_ok=True)
    for f in HERE.glob("*.scs"):
        (d / f.name).write_text(f.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
    (d / "input.scs").write_text(deck, encoding="utf-8", newline="\n")
    r = subprocess.run(["bash", VMRUN.as_posix(), d.as_posix(), f"gt_{tag}"],
                       capture_output=True, text=True)
    return r.returncode, d


def main(argv):
    wanted = set(argv[1:])
    rows = []
    for lib in sorted(HERE.glob("*.scs")):
        if lib.stem in ("nmos_lv", "pmos_lv"):
            continue
        isrc = lib.stem.startswith("isrc")
        for name in subckts(lib):
            if wanted and name not in wanted:
                continue
            rc, d = run(name, tb(lib.name, name, isrc))
            if rc != 0:
                tail = ""
                log = d / "spectre.log"
                if log.exists():
                    tail = [ln for ln in log.read_text(errors="replace").splitlines()
                            if "ERROR" in ln or "Fatal" in ln][:2]
                rows.append((name, "FAIL", "   --", "no", " | ".join(tail)[:90]))
                continue
            op = read_dcop(d / "raw" / "dcOp.dc")
            ac = read_ac(d / "raw" / "acs.ac")
            if isrc:
                idc = abs(op.get("Vout:p", float("nan")))
                curve = ac.get("Vout:p", [])
                ylf = abs(curve[0][1]) if curve else float("nan")
                rows.append((name, "ok", f"{idc*1e6:>8.3f}uA", "yes" if curve else "NO",
                             f"Yout(100Hz) = {ylf:.4g} S  (1/{1/ylf:.4g} ohm)"))
            else:
                vout = op.get("vout", float("nan"))
                curve = ac.get("vout", [])
                tgt, ref = LDO_TARGET.get(name), NGSPICE_REF.get(name)
                err = (vout - tgt) / tgt * 100
                dref = (vout - ref) / ref * 100
                zlf = abs(curve[0][1]) if curve else float("nan")
                fpk, vpk = max(curve, key=lambda fy: abs(fy[1])) if curve else (0, 0)
                rows.append((name, "ok", f"{vout:>9.5f} V", "yes" if curve else "NO",
                             f"design {tgt:.3f} ({err:+.2f}%) | vs ngspice {dref:+.4f}% | "
                             f"|Zout| LF {zlf:.3g}, peak {abs(vpk):.4g} @ {fpk/1e6:.3f} MHz"))

    print(f"\n{'circuit':<28}{'conv':<6}{'DC op':>12}  {'AC':<4} notes")
    for name, status, val, ac_ok, note in rows:
        print(f"{name:<28}{status:<6}{val:>12}  {ac_ok:<4} {note}")
    nfail = sum(1 for r in rows if r[1] != "ok" or r[3] != "yes")
    print(f"\n{len(rows)} circuits, {nfail} failure(s)")
    return 1 if nfail else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
