"""The large-signal tier and the enable ramp.

The load-step droop and the unload overshoot are replayed as an ODE of the model's OWN network,
so the ground truth here is generated by that same forward model with KNOWN `iaG`, `iaV` and
`ovVdz` -- which is exactly the question a port has to answer: does the fit still invert the
forward model it was written for, on this new data contract?

Nothing in `pmukit/fit/` may launch a process, and nothing here does.
"""
import numpy as np
import pytest

from pmukit.config import DerivedConfig
from pmukit.fit import en, load_en, zout
from tests.test_fit_common import CELL, CELL_NOLOAD, RAIL, TEMPS, make, rel, zparams

TIME = np.linspace(0.0, 2e-6, 401)
ZTRUE = zparams(Ra=0.2, La=2e-6, Rpl=40.0, Cout=1e-10, esr=0.2)
VREG, I_OFF, I_ON = 0.8, 2e-6, 5e-3
IAG, IAV, OVVDZ = 3.0e-3, 0.28, 0.020
T0, EDGE = 0.2e-6, 1e-9

DERIVED = DerivedConfig(
    supply={"nominal_v": 1.05},
    rails={RAIL: {}},
    loads={RAIL: {"events": [
        {"event": "tran_load_on", "from_a": I_OFF, "to_a": I_ON, "edge_s": EDGE},
        {"event": "tran_load_off", "from_a": I_ON, "to_a": I_OFF, "edge_s": EDGE}]}})


def wave(i_from, i_to, discharge=None):
    secs = zout.sections_of(ZTRUE)
    sol = load_en.rail_trace(ZTRUE["Ra"], secs, ZTRUE["Cout"], i_from, i_to, IAG, IAV, VREG,
                             T0, EDGE, float(TIME[-1] - T0), discharge=discharge, t_eval=TIME)
    return np.asarray(sol.y[len(secs)], float)


def build(tmp_path, with_unload=True):
    ds = make(tmp_path)
    from tests.test_fit_common import FREQ, declare_ac
    declare_ac(ds, f"ac_zout.{RAIL}", unit="ohm")
    ds.put(f"ac_zout.{RAIL}", CELL, zout.predict(ZTRUE, f=FREQ))
    ds.declare(f"tran_load_on.{RAIL}", dims=("process", "temp_c", "vset", "time_s"),
               dtype="float64", unit="V", coord=TIME)
    ds.put(f"tran_load_on.{RAIL}", CELL_NOLOAD, wave(I_OFF, I_ON))
    if with_unload:
        ds.declare(f"tran_load_off.{RAIL}", dims=("process", "temp_c", "vset", "time_s"),
                   dtype="float64", unit="V", coord=TIME)
        ds.put(f"tran_load_off.{RAIL}", CELL_NOLOAD,
               wave(I_ON, I_OFF, discharge={"ovVdz": OVVDZ}))
    return ds


# --------------------------------------------------------------------------- the assist


def test_the_assist_is_odd_with_zero_slope_at_the_operating_point():
    """`i_assist = iaG*tanh(verr*|verr|/iaV^2)` is ODD with `f'(0) = 0` EXACTLY, which is why
    Zout, PSRR and noise are untouched by it at the operating point."""
    def assist(verr):
        return IAG * np.tanh(verr * abs(verr) / (IAV * IAV))
    for v in (1e-6, 1e-4, 1e-2, 0.1):
        assert assist(-v) == pytest.approx(-assist(v), rel=1e-12)
    h = 1e-9
    assert abs((assist(h) - assist(-h)) / (2 * h)) < 1e-9      # zero slope at the OP


def test_droop_fit_reproduces_the_measured_dip(tmp_path):
    ds = build(tmp_path)
    bf = load_en.fit(ds, RAIL, CELL, DERIVED, zout_params=ZTRUE)
    assert not bf.missing
    assert bf.score < 2.0, bf.notes                            # % error on the droop
    assert bf.metric == "load-step droop % error"
    # one characterized event cannot separate the two assist parameters, and the block must
    # SAY so instead of presenting iaV as a measurement
    assert any("partly degenerate" in n for n in bf.notes)
    assert "iaV" in bf.identifiability["unidentifiable"]
    assert 0.5 * IAG < bf.params["iaG"] < 2.0 * IAG


def test_assist_matches_every_amplitude_and_generalizes_to_a_held_out_one():
    """With more than one step amplitude the two-parameter search runs, and it is gated on the
    DROOPS and on a held-out amplitude -- NOT on the parameter values.

    That is deliberate and documented: `(iaG, iaV)` are partly degenerate, a whole valley
    reproduces the same droops, and the tie-break takes the SMALLEST `iaG` in that valley (the
    gentlest assist that explains the data).  Asserting the planted pair here would be asserting
    the tie-break's position along a valley, which is not what the block claims to measure.
    """
    secs = zout.sections_of(ZTRUE)
    dips = {}
    for i_to in (1e-3, 3e-3, 5e-3):
        dips[(I_OFF, i_to)] = load_en.predict_dip(
            ZTRUE["Ra"], secs, ZTRUE["Cout"], I_OFF, i_to, IAG, IAV, VREG,
            t0=T0, edge=EDGE, tstop=float(TIME[-1] - T0)) * 1e-3
    res = load_en.fit_assist(ZTRUE["Ra"], secs, ZTRUE["Cout"], dips, VREG,
                             t0=T0, edge=EDGE, tstop=float(TIME[-1] - T0))
    assert res is not None
    assert res["_diag"]["single_event"] is False
    assert res["_diag"]["rms_mV"] < 2.0, res["_diag"]
    assert res["_diag"]["held_out"] is not None
    assert abs(res["_diag"]["held_out"]["err_pct"]) < 5.0
    # the fitted pair reproduces the planted droops, which is the claim the block makes
    for (frm, to), dip in dips.items():
        got = load_en.predict_dip(ZTRUE["Ra"], secs, ZTRUE["Cout"], frm, to,
                                  res["iaG"], res["iaV"], VREG,
                                  t0=T0, edge=EDGE, tstop=float(TIME[-1] - T0))
        assert abs(got - dip * 1e3) < 2.5


# --------------------------------------------------------------------------- the discharge


def test_ovvdz_is_fitted_to_the_measured_overshoot(tmp_path):
    ds = build(tmp_path)
    bf = load_en.fit(ds, RAIL, CELL, DERIVED, zout_params=ZTRUE)
    assert rel(bf.params["ovVdz"], OVVDZ) < 0.15, bf.notes
    assert any("MEASURED worst-case overshoot" in n for n in bf.notes)
    assert "ovVdz" not in bf.identifiability["unidentifiable"]


def test_ovvdz_falls_back_to_the_ripple_proxy_and_says_so(tmp_path):
    ds = build(tmp_path, with_unload=False)
    bf = load_en.fit(ds, RAIL, CELL, DERIVED, zout_params=ZTRUE)
    assert any("ripple proxy" in n for n in bf.notes)
    assert "ovVdz" in bf.identifiability["unidentifiable"]
    assert bf.params["ovVdz"] >= load_en.VDZ_MIN


def test_ovvdz_is_a_transparency_floor_and_says_so(tmp_path):
    ds = build(tmp_path)
    bf = load_en.fit(ds, RAIL, CELL, DERIVED, zout_params=ZTRUE)
    assert any("TRANSPARENCY FLOOR, not a droop margin" in n for n in bf.notes)
    assert bf.params["ovVdz"] >= load_en.VDZ_MIN


def test_the_discharge_gate_has_zero_value_and_zero_slope_at_the_operating_point():
    """The one-sided deadzone gate is what keeps Zout, PSRR and noise bit-identical: below the
    deadzone it contributes neither value nor slope."""
    secs = zout.sections_of(ZTRUE)
    quiet = load_en.predict_overshoot(ZTRUE["Ra"], secs, ZTRUE["Cout"], I_ON, I_OFF,
                                      ovVdz=10.0, iaG=IAG, iaV=IAV, vreg=VREG,
                                      t0=T0, edge=EDGE, tstop=float(TIME[-1] - T0))
    engaged = load_en.predict_overshoot(ZTRUE["Ra"], secs, ZTRUE["Cout"], I_ON, I_OFF,
                                        ovVdz=OVVDZ, iaG=IAG, iaV=IAV, vreg=VREG,
                                        t0=T0, edge=EDGE, tstop=float(TIME[-1] - T0))
    assert engaged < quiet                       # a deadzone above every excursion is inert


def test_overshoot_peak_is_monotone_in_the_deadzone():
    """Monotonicity is what makes the deadzone invertible against a measured overshoot."""
    secs = zout.sections_of(ZTRUE)
    peaks = [load_en.predict_overshoot(ZTRUE["Ra"], secs, ZTRUE["Cout"], I_ON, I_OFF, v,
                                       iaG=IAG, iaV=IAV, vreg=VREG, t0=T0, edge=EDGE,
                                       tstop=float(TIME[-1] - T0))
             for v in (2e-3, 8e-3, 2e-2, 5e-2)]
    assert peaks == sorted(peaks)


def test_direction_comes_from_the_declared_currents_not_a_label(tmp_path):
    """A plan whose `tran_load_on` event declares a DECREASING current is a direction the
    fitter must read from `sign(to_a - from_a)`, never from the label."""
    ds = build(tmp_path, with_unload=False)
    bad = DerivedConfig(supply={"nominal_v": 1.05}, rails={RAIL: {}},
                        loads={RAIL: {"events": [{"event": "tran_load_on", "from_a": I_ON,
                                                  "to_a": I_OFF, "edge_s": EDGE}]}})
    bf = load_en.fit(ds, RAIL, CELL, bad, zout_params=ZTRUE)
    assert any("DIRECTION is taken from sign(to_a - from_a)" in n for n in bf.notes)


def test_predict_replays_the_waveform_without_a_simulator(tmp_path):
    ds = build(tmp_path)
    bf = load_en.fit(ds, RAIL, CELL, DERIVED, zout_params=ZTRUE)
    gt = wave(I_OFF, I_ON)
    model = load_en.predict(bf.params, t=TIME, zout=ZTRUE, i_from=I_OFF, i_to=I_ON,
                            vreg=VREG, edge=EDGE, t0=T0)
    assert model.shape == TIME.shape
    # the droop the fit was scored on is reproduced by predict to the same tolerance
    assert rel(VREG - model.min(), VREG - gt.min()) < 0.05


def test_missing_transient_is_missing_not_a_bad_fit(tmp_path):
    ds = make(tmp_path)
    ds.declare(f"tran_load_on.{RAIL}", dims=("process", "temp_c", "vset", "time_s"),
               dtype="float64", unit="V", coord=TIME)
    bf = load_en.fit(ds, RAIL, CELL, DERIVED, zout_params=ZTRUE)
    assert bf.missing is True and bf.params == {}


# --------------------------------------------------------------------------- the EN ramp


def test_en_ramp_recovers_delay_rise_and_overshoot(tmp_path):
    td, tr, over = 1e-6, 2e-6, 0.04 * VREG
    grid = np.linspace(0.0, 1e-5, 301)
    truth = {"t_delay": td, "t_rise": tr, "v_overshoot": over}
    ds = make(tmp_path)
    ds.declare(f"tran_en.{RAIL}", dims=("process", "temp_c", "vset", "time_s"),
               dtype="float64", unit="V", coord=grid)
    ds.put(f"tran_en.{RAIL}", CELL_NOLOAD, en.predict(truth, t=grid, final=VREG, start=0.0))

    bf = en.fit(ds, RAIL, CELL_NOLOAD, DERIVED)
    assert not bf.missing
    assert bf.score < 1.0, bf.notes
    assert rel(bf.params["t_delay"], td) < 0.05
    assert rel(bf.params["t_rise"], tr) < 0.05
    assert rel(bf.params["v_overshoot"], over) < 0.10
    assert bf.params["i_rise"] is None and bf.params["i_overshoot"] is None
    assert any("NOT signed off" in n for n in bf.notes)


def test_en_ramp_of_a_bias_fills_the_current_fields(tmp_path):
    grid = np.linspace(0.0, 1e-5, 301)
    truth = {"t_delay": 5e-7, "i_rise": 1e-6, "i_overshoot": 0.0}
    ds = make(tmp_path)
    ds.declare("tran_en.IB_PTAT", dims=("process", "temp_c", "vset", "time_s"),
               dtype="float64", unit="A", coord=grid)
    ds.put("tran_en.IB_PTAT", CELL_NOLOAD,
           en.predict(truth, t=grid, final=5e-7, start=0.0))
    bf = en.fit(ds, "IB_PTAT", CELL_NOLOAD,
                DerivedConfig(biases={"IB_PTAT": {"vcomp_v": 0.4}}))
    assert bf.params["i_rise"] is not None
    assert bf.params["t_rise"] is None and bf.params["v_overshoot"] is None
    assert rel(bf.params["i_rise"], truth["i_rise"]) < 0.10


def test_en_cell_is_per_corner_and_temperature(tmp_path):
    grid = np.linspace(0.0, 1e-5, 301)
    ds = make(tmp_path)
    ds.declare(f"tran_en.{RAIL}", dims=("process", "temp_c", "vset", "time_s"),
               dtype="float64", unit="V", coord=grid)
    for T in TEMPS:
        ds.put(f"tran_en.{RAIL}", dict(CELL_NOLOAD, temp_c=T),
               en.predict({"t_delay": 1e-6, "t_rise": 2e-6, "v_overshoot": 0.0},
                          t=grid, final=VREG, start=0.0))
    bf = en.fit(ds, RAIL, dict(CELL_NOLOAD, temp_c=125.0), DERIVED)
    assert bf.cell == {"process": "tt", "temp_c": 125.0}
