#!/usr/bin/env python3
"""Commit gate: refuse customer identifiers into this PUBLIC repo.

Reads `.pmukit-denylist` (one token per line, git-ignored, generated by tools/make_denylist.py)
and scans the files about to be committed.  A hit is a hard refusal -- the fix is to change the
FILE, never the gate.

    python tools/guard.py --staged          # what git would commit (pre-commit hook)
    python tools/guard.py PATH [PATH ...]   # explicit files
    python tools/guard.py --all             # every tracked text file
    python tools/guard.py --selftest        # prove the gate bites, with synthetic tokens

Matching is case-insensitive and word-ish: a token matches when it appears surrounded by
anything that is not [A-Za-z0-9_].  That catches `VDD_RAIL_X` inside `xi.VDD_RAIL_X` while not
firing on a longer unrelated identifier that merely contains the token as a substring of a word.
Tokens shorter than 3 characters are ignored (too noisy).
"""
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parent.parent
DENYLIST = REPO / ".pmukit-denylist"
MIN_TOKEN = 3
# Binary-ish or generated files we never scan.
SKIP_SUFFIX = {".png", ".jpg", ".jpeg", ".gif", ".pdf", ".npy", ".npz", ".psf", ".psfbin",
               ".raw", ".zip", ".gz", ".whl", ".ico", ".woff", ".woff2", ".sqlite"}


def load_tokens(path: pathlib.Path = DENYLIST) -> list[str]:
    if not path.exists():
        return []
    out = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        tok = line.strip()
        if not tok or tok.startswith("#"):
            continue
        if len(tok) < MIN_TOKEN:
            continue
        out.append(tok)
    return sorted(set(out), key=lambda t: (-len(t), t.lower()))


def build_pattern(tokens: list[str]) -> re.Pattern | None:
    if not tokens:
        return None
    alt = "|".join(re.escape(t) for t in tokens)
    # (?<![A-Za-z0-9_])TOKEN(?![A-Za-z0-9_])
    return re.compile(rf"(?<![A-Za-z0-9_])(?:{alt})(?![A-Za-z0-9_])", re.IGNORECASE)


def staged_files() -> list[pathlib.Path]:
    try:
        out = subprocess.run(["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR"],
                             cwd=REPO, capture_output=True, text=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError):
        return []
    return [REPO / p for p in out.splitlines() if p.strip()]


def tracked_files() -> list[pathlib.Path]:
    try:
        out = subprocess.run(["git", "ls-files"], cwd=REPO,
                             capture_output=True, text=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError):
        return []
    return [REPO / p for p in out.splitlines() if p.strip()]


def scan_file(path: pathlib.Path, pat: re.Pattern) -> list[tuple[int, str, str]]:
    """Return [(lineno, token, line)] hits."""
    if path.suffix.lower() in SKIP_SUFFIX or not path.is_file():
        return []
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    hits = []
    for i, line in enumerate(text.splitlines(), 1):
        m = pat.search(line)
        if m:
            hits.append((i, m.group(0), line.strip()[:120]))
    return hits


def scan(paths, tokens) -> list[tuple[pathlib.Path, int, str, str]]:
    pat = build_pattern(tokens)
    if pat is None:
        return []
    found = []
    for p in paths:
        # never scan the denylist itself
        try:
            if p.resolve() == DENYLIST.resolve():
                continue
        except OSError:
            pass
        for lineno, tok, line in scan_file(p, pat):
            found.append((p, lineno, tok, line))
    return found


def _report(found) -> None:
    print("pmukit commit gate: customer identifiers found -- REFUSING.", file=sys.stderr)
    print("", file=sys.stderr)
    for p, lineno, tok, line in found:
        try:
            rel = p.relative_to(REPO)
        except ValueError:
            rel = p
        print(f"  {rel}:{lineno}: {tok!r}   {line}", file=sys.stderr)
    print("", file=sys.stderr)
    print("  What : a name from .pmukit-denylist is about to enter a PUBLIC repo.", file=sys.stderr)
    print("  Why  : this repo is tool-only; real cells/nets/projects live under $PMUKIT_DATA.", file=sys.stderr)
    print("  Do   : change the FILE (synthesize the name), never the gate or the denylist.", file=sys.stderr)
    print("  Where: the file:line pairs above; denylist at .pmukit-denylist", file=sys.stderr)


def selftest() -> int:
    """Prove the gate bites -- with synthetic tokens, in a temp dir."""
    toks = ["ACMECHIP7", "VDD_SECRET_RAIL", "zz_proj_42"]
    pat = build_pattern(toks)
    assert pat is not None
    ok = True
    with tempfile.TemporaryDirectory() as td:
        d = pathlib.Path(td)
        bad = d / "bad.scs"
        bad.write_text("xi1 (VDD_SECRET_RAIL 0) mysub\n* note: acmechip7 tapeout\n", encoding="utf-8")
        good = d / "good.scs"
        good.write_text("xi1 (vdd_rail_a 0) mysub\n* synthetic demo only\n", encoding="utf-8")
        longer = d / "longer.scs"
        longer.write_text("* ACMECHIP7X is a different word\n", encoding="utf-8")

        hits = scan([bad], toks)
        if len(hits) != 2:
            print(f"selftest FAIL: expected 2 hits in bad.scs, got {len(hits)}", file=sys.stderr)
            ok = False
        if scan([good], toks):
            print("selftest FAIL: clean file flagged", file=sys.stderr)
            ok = False
        if scan([longer], toks):
            print("selftest FAIL: word-boundary leaked (ACMECHIP7X matched)", file=sys.stderr)
            ok = False
    print("guard selftest:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paths", nargs="*", type=pathlib.Path)
    ap.add_argument("--staged", action="store_true", help="scan the git index (pre-commit hook)")
    ap.add_argument("--all", action="store_true", help="scan every tracked file")
    ap.add_argument("--selftest", action="store_true", help="prove the gate bites (synthetic)")
    a = ap.parse_args(argv)

    if a.selftest:
        return selftest()

    tokens = load_tokens()
    if not tokens:
        print("pmukit commit gate: no .pmukit-denylist (or it is empty) -- nothing to check.",
              file=sys.stderr)
        return 0

    if a.staged:
        paths = staged_files()
    elif a.all:
        paths = tracked_files()
    else:
        paths = list(a.paths)
    if not paths:
        return 0

    found = scan(paths, tokens)
    if found:
        _report(found)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
